project:
  type: website
  output-dir: docs

website:
  title: "my-website"
  navbar:
    left:
      - href: index.qmd
        text: about me
      - science.qmd
      - communication.qmd
      - data viz.qmd
      - workshops.qmd
      - resources.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true



