project:
  type: website
  output-dir: docs

website:
  title: "Francisco J. Guerrero"
  site-url: "https://fjguerrero.github.io"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - science.qmd
      - communication.qmd
      - d_data viz.qmd
      - e_workshops.qmd
      - f_resources.qmd


format:
  html:
    theme: 
      light: cosmo
      dark: cyborg
    css: styles.css
    toc: true



