project:
  type: website
  output-dir: docs

website:
  title: "my-website"
  navbar:
    left:
      - href: index.qmd
        text: about me
      - b_science.qmd
      - c_communication.qmd
      - d_data viz.qmd
      - e_workshops.qmd
      - f_resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



